export default {
  data() {
    return {
      portfolios: [
        {
          id: 1,
          img: require(`@/assets/images/portfolio/project-1.jpg`),
          title: "Medical ChatBot PROJECT",
          project: "Medical Chat Bot",
          backend: "www.app.quiobot.com",
          backendLink: "http://www.app.omarelghiba.com/chatbot",
          language: "Python,Javascript,Php,Yaml",
          frontend: "app.omarelghiba.com/chatbot",
          frontendLink: "http://www.app.omarelghiba.com/chatbot",
        },
        {
          id: 2,
          img: require(`@/assets/images/portfolio/project-2.jpg`),
          title: "Digital Marketing AI PROJECT",
          project: "Digital Marketing AI PROJECT",
          backend: "www.app.quiobot.com",
          backendLink: "http://www.omarelghiba.com/platform",
          language: "Python,Javascript,Php,Yaml",
          frontend: "app.omarelghiba.com/platform",
          frontendLink: "http://www.app.omarelghiba.com/platform",
        },
        {
          id: 3,
          img: require(`@/assets/images/portfolio/project-3.jpg`),
          title: "Customer Satisfaction AI",
          project: "Customer Satisfaction AI ",
          backend: "www.app.quiobot.com",
          backendLink: "https://www.app.omarelghiba.com/chatbot",
          language: "Python,Javascript,Php,Yaml",
          frontend: "app.omarelghiba.com/customer",
          frontendLink: "https://www.app.omarelghiba.com/customer",
        },
        {
          id: 4,
          img: require(`@/assets/images/portfolio/project-4.jpg`),
          title: "SearchBar Suggestion",
          project: "SearchBar Suggestion",
          backend: "www.app.quiobot.com",
          backendLink: "https://www.app.omarelghiba.com/searchbar",
          language: "Python,Javascript,Php,Yaml",
          frontend: "app.omarelghiba.com/searchbar",
          frontendLink: "https://www.app.omarelghiba.com/searchbar",
        },
        {
          id: 5,
          img: require(`@/assets/images/portfolio/project-5.jpg`),
          title: "Vuejs - FastAPi - Postgres (Authentication - Sql)",
          project: "Vuejs - FastAPi - Postgres (Authentication)",
          backend: "www.app.quiobot.com",
          backendLink: "http://www.app.omarelghiba.com/",
          language: "Python,Javascript,Sql,Yaml",
          frontend: "www.demo.omarelghiba.com",
          frontendLink: "http://www.demo.omarelghiba.com/",
        },
        {
          id: 6,
          img: require(`@/assets/images/portfolio/project-6.jpg`),
          title: "FastApi - MongoDb (Nosql)",
          project: "Web Application",
          backend: "www.app.quiobot.com",
          backendLink: "https://www.app.omarelghiba.com/chatbot",
          language: "Python,Javascript,Nosql,Yaml",
          frontend: "www.app.quiobot.com",
          frontendLink: "https://www.app.omarelghiba.com/chatbot",
        },
        // {
        //   id: 7,
        //   img: require(`@/assets/images/portfolio/project-7.jpg`),
        //   title: "MOCKUP PROJECT",
        //   project: "Website",
        //   backend: "www.app.quiobot.com",
        //   backendLink: "https://www.app.quiobot.com/chatbot",
        //   language: "Python,Javascript,Php",
        //   frontend: "www.app.quiobot.com",
        //   frontendLink: "https://www.app.quiobot.com/chatbot",
        // },
        // {
        //   id: 8,
        //   img: require(`@/assets/images/portfolio/project-8.jpg`),
        //   title: "FACEBOOK PROJECT",
        //   project: "Shoot",
        //   backend: "www.app.quiobot.com",
        //   backendLink: "https://www.app.quiobot.com/chatbot",
        //   language: "Python,Javascript,Php",
        //   frontend: "www.app.quiobot.com",
        //   frontendLink: "https://www.app.quiobot.com/chatbot",
        // },
        // {
        //   id: 9,
        //   img: require(`@/assets/images/portfolio/project-9.jpg`),
        //   title: "LINKEDIN PROJECT",
        //   project: "Website",
        //   backend: "www.app.quiobot.com",
        //   backendLink: "https://www.app.quiobot.com/chatbot",
        //   language: "Python,Javascript,Php",
        //   frontend: "www.app.quiobot.com",
        //   frontendLink: "https://www.app.quiobot.com/chatbot",
        // },
      ],
    };
  },
};
