export default {
  data() {
    return {
      portfolios: [
        {
          id: 1,
          img: require(`@/assets/images/portfolio/project-1.jpg`),
          title: "Medical ChatBot AI",
          project: "Medical ChatBot AI",
          github: "Go",
          githubLink: "https://github.com/omar-elghiba/QuiBot-ChatBot",
          language: "Python,Javascript,Php,Yaml",
          website: "Go",
          websiteLink: "http://bot.omarelghiba.com/#/chatbot",
          login: "",
          loginLink: "",
        },
        {
          id: 2,
          img: require(`@/assets/images/portfolio/project-2.jpg`),
          title: "Digital Marketing AI",
          project: "Digital Marketing AI",
          github: "Go",
          githubLink: "https://github.com/omar-elghiba/Quibot-Digital-Marketing",
          language: "Python,Javascript,Yaml",
          website: "Go",
          websiteLink: "http://bot.omarelghiba.com/#/platform",
          login: "Go",
          loginLink: "http://157.245.17.232/#/email_marketing",
        },
        {
          id: 3,
          img: require(`@/assets/images/portfolio/project-3.jpg`),
          title: "Customer Satisfaction AI",
          project: "Customer Satisfaction AI ",
          github: "Go",
          githubLink: "https://github.com/omar-elghiba/QuiBot-Customer-Satisfaction",
          language: "Python,Javascript,Php,Yaml",
          website: "Go",
          websiteLink: "http://bot.omarelghiba.com/#/customer",
          login: "",
          loginLink: "",
        },
        {
          id: 4,
          img: require(`@/assets/images/portfolio/project-4.jpg`),
          title: "SearchBar Suggestion AI",
          project: "SearchBar Suggestion AI",
          github: "Go",
          githubLink: "https://github.com/omar-elghiba/QuioBot-SearchBar-Suggestion",
          language: "Python,Javascript,Php,Yaml",
          website: "",
          websiteLink: "",
          login: "",
          loginLink: "",
        },
        {
          id: 5,
          img: require(`@/assets/images/portfolio/project-5.jpg`),
          title: "Vuejs - FastAPi - Postgres - Docker - Google Kubernetes Engine (Authentication)",
          project: "Vuejs - FastAPi - Postgres",
          github: "Go",
          githubLink: "https://github.com/omar-elghiba/Quiobot-Sql-Postgres",
          language: "Python,Javascript,Sql,Yaml",
          website: "Go",
          websiteLink: "http://demo.omarelghiba.com/",
          login: "Go",
          loginLink: "http://demo.omarelghiba.com/#/login",
        },
        {
          id: 6,
          img: require(`@/assets/images/portfolio/project-6.jpg`),
          title: "FastApi - MongoDb (Nosql)",
          project: "FastApi - MongoDb (Nosql)",
          github: "Go",
          githubLink: "https://github.com/omar-elghiba/QuioBot-Nosql-Mongodb",
          language: "Python,Javascript,Nosql",
          website: "",
          websiteLink: "",
          login: "",
          loginLink: "",
        },
        // {
        //   id: 7,
        //   img: require(`@/assets/images/portfolio/project-7.jpg`),
        //   title: "MOCKUP PROJECT",
        //   project: "Website",
        //   backend: "www.app.quiobot.com",
        //   backendLink: "https://www.app.quiobot.com/chatbot",
        //   language: "Python,Javascript,Php",
        //   frontend: "www.app.quiobot.com",
        //   frontendLink: "https://www.app.quiobot.com/chatbot",
        // },
        // {
        //   id: 8,
        //   img: require(`@/assets/images/portfolio/project-8.jpg`),
        //   title: "FACEBOOK PROJECT",
        //   project: "Shoot",
        //   backend: "www.app.quiobot.com",
        //   backendLink: "https://www.app.quiobot.com/chatbot",
        //   language: "Python,Javascript,Php",
        //   frontend: "www.app.quiobot.com",
        //   frontendLink: "https://www.app.quiobot.com/chatbot",
        // },
        // {
        //   id: 9,
        //   img: require(`@/assets/images/portfolio/project-9.jpg`),
        //   title: "LINKEDIN PROJECT",
        //   project: "Website",
        //   backend: "www.app.quiobot.com",
        //   backendLink: "https://www.app.quiobot.com/chatbot",
        //   language: "Python,Javascript,Php",
        //   frontend: "www.app.quiobot.com",
        //   frontendLink: "https://www.app.quiobot.com/chatbot",
        // },
      ],
    };
  },
};
